
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SwapMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    public Book()
    {

        this.SwapItem = new HashSet<SwapItem>();

        this.SwapTransaction = new HashSet<SwapTransaction>();

    }


    public int ID { get; set; }

    public int AccID { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public int CategoryID { get; set; }

    public string Publisher { get; set; }

    public Nullable<decimal> PblYear { get; set; }

    public string Descrptn { get; set; }

    public Nullable<int> Price { get; set; }

    public string BookImage { get; set; }

    public string BookStatus { get; set; }

    public string City { get; set; }

    public string DetailAddr { get; set; }

    public System.DateTime PostDate { get; set; }

    public Nullable<System.DateTime> DueDate { get; set; }



    public virtual Account Account { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<SwapItem> SwapItem { get; set; }

    public virtual ICollection<SwapTransaction> SwapTransaction { get; set; }

}

}
