
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SwapMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int ID { get; set; }

    public int SwapItemID { get; set; }

    public int AccID { get; set; }

    public string Content { get; set; }

    public System.DateTime CommentDate { get; set; }



    public virtual Account Account { get; set; }

    public virtual SwapItem SwapItem { get; set; }

}

}
