
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SwapMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SwapItem
{

    public SwapItem()
    {

        this.Comment = new HashSet<Comment>();

        this.SwapTransaction = new HashSet<SwapTransaction>();

    }


    public int ID { get; set; }

    public int BookID { get; set; }

    public int AccID { get; set; }

    public string ItemType { get; set; }

    public string ItemTitle { get; set; }

    public string ItemDcrpt { get; set; }

    public string ItemImage { get; set; }

    public Nullable<int> Price { get; set; }

    public string ItemStatus { get; set; }

    public System.DateTime PostDate { get; set; }



    public virtual Account Account { get; set; }

    public virtual Book Book { get; set; }

    public virtual ICollection<Comment> Comment { get; set; }

    public virtual ICollection<SwapTransaction> SwapTransaction { get; set; }

}

}
